# Generated by Django 3.2.14 on 2022-08-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comment_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='the_comment',
            field=models.ManyToManyField(blank=True, related_name='the_comment', to='network.Comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='the_like',
            field=models.ManyToManyField(blank=True, related_name='the_like', to='network.Like'),
        ),
    ]
