# Generated by Django 3.1.7 on 2022-08-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20220812_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='likes_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='the_comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='the_like',
        ),
    ]
